Parameters:
  VpcName:
    Description: Choose which VPC to use
    Type: String
  InstanceType:
    Description: Instance type
    Type: String
    Default: t3.2xlarge
Resources:
  rCloud9Environment:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      AutomaticStopTimeMinutes: 30
      ConnectionType: CONNECT_SSM
      Description: Web-based cloud development environment
      InstanceType: !Ref 'InstanceType'
      Name: Cloud9Environment
      Repositories: 
        - PathComponent: /repos/codecommit
          RepositoryUrl: !GetAtt rCloud9WorkingRepository.CloneUrlHttp
        - PathComponent: /repos/aws-cloud9-environment
          RepositoryUrl: https://github.com/nkasrawi/aws-cloud9-environment.git
      SubnetId: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'VpcName'
            - 'PublicSubnetA'
      ImageId: amazonlinux-2-x86_64
      OwnerArn: arn:aws:sts::254508885371:assumed-role/ADFS-Devops-Admin/nawwar.kasrawi@siriusxm.com
  rCloud9WorkingRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: Cloud9WorkingRepository
      RepositoryDescription: A CodeCommit repository for stashing work from the Cloud9 IDE
